apiVersion: v1
kind: Service
metadata:
  name: gitea-external
  namespace: virida
  labels:
    app: gitea-external
spec:
  type: ExternalName
  externalName: gitea.cleverapps.io
  ports:
  - port: 443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitea-external
  namespace: virida
subsets:
- addresses:
  - ip: 185.31.40.1  # IP de votre Gitea sur Clever Cloud (Ã  adapter)
  ports:
  - port: 443
    protocol: TCP
