apiVersion: v1
kind: Namespace
metadata:
  name: virida
  labels:
    name: virida
    app.kubernetes.io/name: virida
    app.kubernetes.io/part-of: virida-infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: virida-infrastructure
