apiVersion: v1
kind: Service
metadata:
  name: virida-ihm-external
  namespace: virida
  labels:
    app: virida-ihm-external
spec:
  type: ExternalName
  externalName: virida-ihm.cleverapps.io
  ports:
  - port: 443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: virida-ihm-external
  namespace: virida
subsets:
- addresses:
  - ip: 185.31.40.1  # IP de votre virida_ihm sur Clever Cloud (Ã  adapter)
  ports:
  - port: 443
    protocol: TCP
